[tools]
gitleaks = "latest"
shellcheck = "latest"
trufflehog = "latest"
shfmt = "latest"
hk = "latest"
pkl = "latest"
lychee = "latest"
prettier = "latest"
just = "latest"
fnox = "latest"

[env]
HK_MISE = 1
