# initialize or update chezmoi dotfiles
cm:
    $(op read op://homelab/svc/bash) \
    ; chezmoi init chrishenn -a --force \
    ; chezmoi update -a --force

# full upgrade of package manager packages
topgrade:
    $(op read op://homelab/svc/bash) \
    ; topgrade

# 'git clone' all repos for the default user. default dir: ~/
gclone:
    $(op read op://homelab/svc/bash) \
    ; ~/gclone.sh

_ssh usr ip dir="/home" port="22":
    ssh {{ usr }}@{{ ip }} -p {{ port }} -t "$(op read op://homelab/svc/bash) && cd {{ dir }} && exec bash -l"

rack0: (_ssh "$RACK0_USR" "$RACK0_IP" "$RACK0_DIR" "$RACK0_PORT")

rack4: (_ssh "$RACK4_USR" "$RACK4_IP" "$RACK4_DIR" "$RACK4_PORT")

vps0: (_ssh "$VPS0_USR" "$VPS0_IP" "$VPS0_DIR" "$VPS0_PORT")