default_provider = "onepass"
if_missing = "error"

[providers.onepass]
type = "1password"
vault = "homelab"
account = "my.1password.com"

[providers.age]
type = "age"
recipients = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBDbuPSH93RCTHG7iTHxg+De/yMWUVB+Q4EFt4llpPDL"]

[secrets]
GITHUB_TOKEN= { provider = "onepass", value = "op://homelab/github/credential" }
