[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[aws]
disabled = true
symbol = 'aws '
format = '[$symbol$profile]($style) | '

[bun]
symbol = 'bun '
format = '[$symbol$version]($style) | '

[c]
symbol = 'c '
format = '[$symbol($version(-$name))]($style) | '

[cpp]
symbol = 'cpp '
format = '[$symbol($version(-$name))]($style) | '

[cmake]
symbol = 'cmake '
format = '[$symbol$version]($style) | '

[cmd_duration]
format = '[$duration]($style) | '

[cobol]
symbol = 'cobol '
format = '[$symbol$version]($style) | '

[conda]
symbol = 'conda '
format = '[$symbol$environment]($style) | '

[container]
disabled = true
symbol = 'container '
format = '[$symbol$name]($style) | '

[crystal]
symbol = 'crystal '
format = '[$symbol$version]($style) | '

[daml]
symbol = 'daml '
format = '[$symbol$version]($style) | '

[dart]
symbol = 'dart '
format = '[$symbol$version]($style) | '

[deno]
symbol = 'deno '
format = '[$symbol$version]($style) | '

[docker_context]
symbol = 'docker '
format = '[$symbol$context]($style) | '

[dotnet]
symbol = 'dotnet '
format = '[$symbol$version$tfm]($style) | '

[elixir]
symbol = 'elixir '
format = '[$symbol($version \(OTP $otp_version\))]($style) | '

[elm]
symbol = 'elm '
format = '[$symbol$version]($style) | '

[erlang]
symbol = 'erlang '
format = '[$symbol$version]($style) | '

[fennel]
symbol = 'fennel '
format = '[$symbol$version]($style) | '

[fossil_branch]
symbol = 'fossil '
format = '[$symbol$branch]($style) | '

[gcloud]
symbol = 'gcloud '
format = '[$symbol$account(@$domain)(\($region\))]($style) | '

[git_branch]
symbol = "git "
format = '[$symbol$branch]($style) | '

[git_commit]
tag_symbol = " tag "

[git_status]
disabled = true
format = '[$all_status$ahead_behind]($style) | '

[golang]
symbol = 'golang '
format = '[$symbol$version]($style) | '

[gradle]
symbol = 'gradle '
format = '[$symbol$version]($style) | '

[guix_shell]
symbol = 'guix '
format = '[$symbol]($style) | '

[haskell]
symbol = 'haskell '
format = '[$symbol$version]($style) | '

[haxe]
symbol = 'haxe '
format = '[$symbol$version]($style) | '

[helm]
symbol = 'helm '
format = '[$symbol$version]($style) | '

[hg_branch]
symbol = 'hg '
format = '[$symbol$branch]($style) | '

[hostname]
ssh_only = false
format = '[$hostname](bold red) '

[java]
symbol = 'java '
format = '[$symbol$version]($style) | '

[julia]
symbol = 'julia '
format = '[$symbol$version]($style) | '

[kotlin]
symbol = 'kotlin '
format = '[$symbol$version]($style) | '

[kubernetes]
symbol = 'k8s '
format = '[$symbol$context( \($namespace\))]($style) | '

[lua]
symbol = 'lua '
format = '[$symbol$version]($style) | '

[memory_usage]
symbol = 'memory '
format = '|$symbol[$ram( | $swap)]($style) | '

[meson]
symbol = 'meson '
format = '[$symbol$project]($style) | '

[mise]
disabled = true
symbol = 'mise '
format = '[$symbol$health]($style) | '

[mojo]
symbol = 'mojo '
format = '[$symbol$version]($style) | '

[nim]
symbol = 'nim '
format = '[$symbol$version]($style) | '

[nix_shell]
symbol = 'nix '
format = '[$symbol$state( \($name\))]($style) | '

[nodejs]
symbol = 'node '
format = '[$symbol$version]($style) | '

[ocaml]
symbol = 'ocaml '
format = '[$symbol$version(\($switch_indicator$switch_name\))]($style) | '

[opa]
symbol = 'opa '
format = '[$symbol$version]($style) | '

[os]
format = '[$symbol]($style) | '

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
Bluefin = "blfn "
CachyOS = "cach "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
Nobara = "nbra "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Uos = "uos "
Void = "void "
Windows = "win "

[openstack]
symbol = 'openstack '
format = '[$symbol$cloud(\($project\))]($style) | '

[package]
disabled = true
symbol = 'package '
format = '[$symbol$version]($style) | '

[perl]
symbol = 'perl '
format = '[$symbol$version]($style) | '

[php]
symbol = 'php '
format = '[$symbol$version]($style) | '

[pijul_channel]
symbol = 'pijul '
format = '[$symbol$channel]($style) | '

[pixi]
detect_files = ['pixi.toml']
detect_folders = []
style = 'bold blue'
symbol = 'pixi '
format = '[$symbol($environment)]($style) | '

[pulumi]
symbol = 'pulumi '
format = '[$symbol$stack]($style) | '

[purescript]
symbol = 'purescript '
format = '[$symbol$version]($style) | '

[python]
symbol = 'py '
format = '[$symbol$version]($style) | '
detect_extensions = []

[raku]
symbol = 'raku '
format = '[$symbol($version-$vm_version)]($style) | '

[red]
symbol = 'red '
format = '[$symbol$version]($style) | '

[ruby]
symbol = 'ruby '
format = '[$symbol$version]($style) | '

[rust]
symbol = 'rust '
format = '[$symbol$version]($style) | '

[scala]
symbol = 'scala '
format = '[$symbol$version]($style) | '

[spack]
symbol = 'spack '
format = '[$symbol$environment]($style) | '

[sudo]
symbol = 'sudo '
format = '[as $symbol]($style) | '

[swift]
symbol = 'swift '
format = '[$symbol$version]($style) | '

[terraform]
symbol = 'terraform '
format = '[$symbol$workspace]($style) | '

[time]
format = '[$time]($style) | '

[username]
disabled = true
format = '[$user]($style) | '

[vagrant]
symbol = 'vagrant '
format = '[$symbol$version]($style) | '

[vlang]
symbol = 'vlang '
format = '[$symbol$version]($style) | '

[zig]
symbol = 'zig '
format = '[$symbol$version]($style) | '

[solidity]
symbol = 'solidity '
format = '[$symbol$version]($style) | '
