[defaults]
profile = "default"
binary_only = false

[packages]
ghostty = "*"
helium-browser = "*"
localsend = "*"
signal-desktop = "8.16.0-1"
discord = "*"
btop = "*"

[packages.fluxer]
url = "https://api.fluxer.app/dl/desktop/stable/linux/x64/{version}/appimage"
version = "0.0.8"
version_command = "curl -qfsSLI https://api.fluxer.app/dl/desktop/stable/linux/x64/latest/appimage | rg 'fluxer-stable-(.*)-x86_64.AppImage' -or '$1'"

[packages.kicad]
url = "https://mirrors.mit.edu/kicad/appimage/stable/kicad-{version}-x86_64.AppImage.tar"
hooks = {post_download = "7z x kicad"}
pinned = true
version = "10.0.2"
version_command = "curl -qfsSL https://api.github.com/repos/KiCad/kicad-source-mirror/releases/latest | rg -m 1 'kicad-(.*)-x86_64' -or '$1'"

[packages.arduino]
github = "arduino/arduino-ide"
asset_pattern = "arduino-ide_*_Linux_64bit.AppImage"
pinned = true
version = "2.3.8"

[packages.vscodium]
github = "vscodium/vscodium"
asset_pattern = "VSCodium-*.glibc*-x86_64.AppImage"
version = "1.121.03429"
ls
[packages.prusaslicer]
github = "sarrchri/PrusaSlicer.AppImage"
asset_pattern = "PrusaSlicer-*-anylinux-x86_64.AppImage"
version = "2.9.5-1@2026-05-22_1779472316"

[packages.handy]
github = "cjpais/handy"
asset_pattern = "Handy_*_amd64.AppImage"
version = "0.8.3"

[packages.caligula]
github = "ifd3f/caligula"
asset_pattern = "caligula-x86_64-linux"
version = "0.5.0"

[packages.yaak]
github = "mountain-loop/yaak"
asset_pattern = "yaak_*_amd64.AppImage"
version = "2026.4.0"
