[tools]
uv = "latest"
rust = "stable"
go = "latest"
pixi = "latest"
zig = "latest"
zls = "latest"
lua = "latest"

node = "latest"
npm = "latest"
pnpm = "latest"
bun = "latest"

bazel = "latest"
clang = "21.1.4"
cmake = "latest"
ninja = "latest"
meson = "latest"

dust = "latest"
semver = "latest"
bottom = "latest"
gh = "latest"
bat = "latest"
eza = "latest"
jless = "latest"
sd = "latest"
fd = "latest"
rg = "latest"
jq = "latest"
yq = "latest"
jqp = "latest"
yazi = "latest"
zoxide = "latest"
starship = "latest"
powershell = "latest"
zellij = "latest"
chezmoi = "latest"

aws-cli = "latest"
pulumi = "latest"
hk = "latest"
pkl = "latest"
prettier = "next"
gitleaks = "latest"
trufflehog = "latest"
just = "latest"
ruff = "latest"
pre-commit = "latest"
shfmt = "latest"
shellcheck = "latest"
mask = "latest"

"cargo:dysk" = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:topgrade" = "latest"
"ubi:gitlab-org/cli" = { version = "latest", exe = "glab", provider = "gitlab" }
"cargo:tealdeer" = "latest"
"cargo:nu" = "latest"

[settings]
experimental = true

[env]
TERM = "xterm-256color"
KUBE_EDITOR = "nano"
COMPOSE_BAKE = true
OP_RUN_NO_MASKING=true
HK_MISE = 1
UV_PREVIEW = 1
MISE_NPM_BUN = 1

[tasks.sysupg]
description = "Full system upgrade"
run = "topgrade -y --no-retry --disable uv jetbrains_toolbox jetbrains_pycharm vscode"
