# linux tools (desktop)
[tools]
op = "latest"
semver = "latest"
dust = "latest"
bottom = "latest"
gh = "latest"
bat = "latest"
eza = "latest"
jless = "latest"
fd = "latest"
rg = "latest"
jq = "latest"
sd = "latest"
yq = "latest"
jqp = "latest"
yazi = "latest"
fzf = "latest"

starship = "latest"
zoxide = "latest"
atuin = "latest"
tmux = "latest"
zellij = "latest"
"aqua:joshmedeski/sesh" = "latest"

chezmoi = "latest"
just = "latest"
fnox = "latest"
powershell = "latest"
television = "latest"
rclone = "latest"
aws-cli = "latest"
ruff = "latest"
shellcheck = "latest"

rust = "latest"
go = "latest"
zig = "latest"
zls = "latest"
#lua = "latest"

node = "latest"
npm = "latest"
pnpm = "latest"
bun = "latest"

"cargo:tealdeer" = "latest"
"cargo:tokei" = "latest"
"cargo:dysk" = "latest"
"cargo:nu" = "latest"
"cargo:topgrade" = "latest"
"cargo:cargo-update" = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-dist" = "latest"

[bootstrap.brew]
adopt = true

[bootstrap.brew.taps]
"stalwartlabs/tap" = "https://github.com/stalwartlabs/homebrew-tap.git"
"valkyrie00/bbrew" = "https://github.com/valkyrie00/homebrew-bbrew.git"
"ublue-os/tap" = "https://github.com/ublue-os/homebrew-tap.git"

[bootstrap.packages]
"brew:atuin" = "latest"
"brew:valkyrie00/bbrew/bbrew" = "latest"
"brew:detect-secrets" = "latest"
"brew:feroxbuster" = "latest"
"brew:media-info" = "latest"
"brew:parallel" = "latest"
"brew:sevenzip" = "latest"
"brew:stalwartlabs/tap/stalwart-cli" = "latest"
"brew:trash-cli" = "latest"

# only font "tapped casks" are supported by mise right now
# "brew-cask:ublue-os/tap/zed-linux" = "latest"
# "brew-cask:ublue-os/tap/1password-gui-linux" = "latest"
# "brew-cask:ublue-os/tap/jetbrains-toolbox-linux" = "latest"
"brew-cask:font-fira-code-nerd-font" = "latest"
"brew-cask:font-jetbrains-mono-nerd-font" = "latest"

"flatpak:md.obsidian.Obsidian" = "latest"
"flatpak:io.github.cboxdoerfer.FSearch" = "latest"
"flatpak:com.prusa3d.PrusaSlicer" = "latest"
"flatpak:com.github.wwmm.easyeffects" = "latest"
"flatpak:org.onlyoffice.desktopeditors" = "latest"
"flatpak:org.kde.kdenlive" = "latest"
"flatpak:com.belmoussaoui.Obfuscate" = "latest"
"flatpak:io.gitlab.adhami3310.Converter" = "latest"
"flatpak:org.audacityteam.Audacity" = "latest"
"flatpak:org.darktable.Darktable" = "latest"

# sudo timeout
[bootstrap.files."/etc/sudoers.d/sudo_timeout"]
content = "Defaults timestamp_timeout=180"
owner = "root"
group = "root"
mode = "0440"

# sysctl
[bootstrap.files."/etc/sysctl.d/99-custom.conf"]
content = """
net.ipv4.ip_nonlocal_bind=1
vm.overcommit_memory=1
fs.inotify.max_user_watches=1014796
fs.inotify.max_user_instances=1014796
fs.inotify.max_queued_events=1014796
net.ipv6.conf.all.disable_ipv6=1
"""
owner = "root"
group = "root"
mode = "0644"

# power_shortcuts
[bootstrap.files."~/.local/share/applications/restart.desktop"]
template = true
content = """
[Desktop Entry]
Name=Restart
Exec=bash -c "sudo {{ env.HOME }}/.local/share/applications/restart.sh"
Comment=Restart
Terminal=true
Type=Application
Icon=system-reboot
"""

[bootstrap.files."~/.local/share/applications/shutdown.desktop"]
template = true
content = """
[Desktop Entry]
Name=Shutdown
Exec=bash -c "sudo {{ env.HOME }}/.local/share/applications/shutdown.sh"
Comment=Shutdown
Terminal=true
Type=Application
Icon=system-shutdown
"""

[bootstrap.files."~/.local/share/applications/restart.sh"]
content = "reboot now"
mode = "0755"

[bootstrap.files."~/.local/share/applications/shutdown.sh"]
content = "shutdown now"
mode = "0755"

[bootstrap.files."/etc/sudoers.d/pwr"]
content = """
{{ env.USER }} ALL=(root) NOPASSWD:{{ env.HOME }}/.local/share/applications/shutdown.sh
{{ env.USER }} ALL=(root) NOPASSWD:{{ env.HOME }}/.local/share/applications/restart.sh
"""
template = true
owner = "root"
group = "root"
mode = "0440"

[bootstrap.hooks.post-packages]
run = """
# flatpak fix: a bunch didn't launch ootb due to file perm issue
systemctl --user restart xdg-document-portal.service
# allow obs droidcam to access media devices?
flatpak override --user --device=all com.obsproject.Studio
# docker device runtime
sudo nvidia-ctk runtime configure --runtime=docker --set-as-default --quiet
"""

[bootstrap.hooks.final]
run = """
# sysctl settings apply
sudo sysctl --system -q
"""
